do-op:
	cc -Wall -Wextra -Werror -c ft_calc.c -o ft_calc.o
	cc -Wall -Wextra -Werror -c ft_do-op.c -o ft_do-op.o
	cc -Wall -Wextra -Werror -c ft_new_atoi.c -o ft_new_atoi.o
	cc -Wall -Wextra -Werror -c ft_putnbr.c -o ft_putnbr.o
	cc -o do-op ft_calc.o ft_do-op.o ft_new_atoi.o ft_putnbr.o

clean:
	rm -f do-op ft_calc.o ft_do-op.o ft_new_atoi.o ft_putnbr.o